site_name: Computer Architecture Learning Notes
site_url: https://bwoah-kimi.github.io/Computer_architecture_learning_notes/
site_author: Bwoah-Kimi
copyright: Copyright &copy; 2024 School of Integrated Circuits, Peking University

repo_url: https://github.com/Bwoah-Kimi/Computer_architecture_learning_notes
repo_name: GitHub Repo
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  language: zh
  logo: figs/pku_logo.png
  favicon: figs/pku_logo_red.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: custom
      accent: pink
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    code: JetBrainsMono
  features:
    - navigation.top
    - navigation.instant
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - content.action.view
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.arithmatex

plugins:
  - search:
      lang:
        - zh
        - en
  - git-revision-date-localized:
      enable_creation_date: true
  - git-committers:
      repository: Bwoah-Kimi/Computer_architecture_learning_notes
      branch: main
      token: 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
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true

extra_css:
  - extra.css

extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  - Welcome to my Learning Notes on Computer Architecture!: 0_index.md
  - I. Fundamentals of Computer Architecture:
    - 1. Quantitative Principles of Computer Design: 1_quantitative_principles.md
    - 2. Introduction to Computer Architecture: 2_introduction_to_computer_architecture.md
    - 3. Pipelining: 4_pipelining.md
    - 4. Out-of-Order Execution: 5_out_of_order_execution.md
  - II. Memory System:
    - 1. Memory Hierarchy: 3_memory_hierarchy.md