[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "computer_architecture"
authors = [{name = "tombstone_blues", email = "jameszhu.20021122@gmail.com"}]
dynamic = ["version", "description"]
